import { 
  collection, 
  addDoc, 
  onSnapshot, 
  query, 
  orderBy, 
  where, 
  doc, 
  updateDoc, 
  Timestamp,
  getDocs
} from 'firebase/firestore';
import { db } from './firebase';

export interface FIRData {
  id?: string;
  caseNumber: string;
  date: Timestamp;
  touristId: string;
  touristName: string;
  touristEmail: string;
  touristPhone?: string;
  incidentType: string;
  incidentDetails: string;
  location: {
    latitude: number;
    longitude: number;
    address?: string;
  };
  district: string;
  policeStation: string;
  status: 'Active' | 'Under Investigation' | 'Closed' | 'Pending';
  priority: 'High' | 'Medium' | 'Low';
  createdAt: Timestamp;
  updatedAt: Timestamp;
  isAutoGenerated: boolean;
  emergencyId?: string;
  investigatingOfficer?: string;
  section?: string;
  additionalDetails?: string;
}

export interface EmergencyData {
  touristId: string;
  isInDistress: boolean;
  location: {
    latitude: number;
    longitude: number;
  };
  lastUpdatedAt: Timestamp;
  name?: string;
  email?: string;
  phone?: string;
}

// Generate unique FIR case number (in-memory counter)
let firCounter = 0;
export const generateFIRNumber = (): string => {
  const year = new Date().getFullYear();
  const month = String(new Date().getMonth() + 1).padStart(2, '0');
  
  firCounter++;
  const sequentialNumber = String(firCounter).padStart(3, '0');
  
  return `NE-${year}-${month}-${sequentialNumber}`;
};

// Determine police station based on location (simplified mapping)
export const getPoliceStationByLocation = (latitude: number, longitude: number): { district: string; policeStation: string } => {
  // This is a simplified mapping. In a real application, you would use a more sophisticated
  // geolocation service or database to determine the exact police station jurisdiction
  
  // Assam
  if (latitude >= 25.5 && latitude <= 27.5 && longitude >= 89.5 && longitude <= 96.0) {
    if (latitude >= 26.0 && latitude <= 26.3 && longitude >= 91.5 && longitude <= 91.8) {
      return { district: 'Guwahati', policeStation: 'Fancy Bazar Police Station' };
    }
    return { district: 'Guwahati', policeStation: 'Dispur Police Station' };
  }
  
  // Meghalaya
  if (latitude >= 25.0 && latitude <= 26.0 && longitude >= 90.0 && longitude <= 92.5) {
    return { district: 'Shillong', policeStation: 'Laitumkhrah Police Station' };
  }
  
  // Tripura
  if (latitude >= 23.0 && latitude <= 24.5 && longitude >= 91.0 && longitude <= 92.5) {
    return { district: 'Agartala', policeStation: 'West Agartala Police Station' };
  }
  
  // Nagaland
  if (latitude >= 25.2 && latitude <= 27.0 && longitude >= 93.2 && longitude <= 95.2) {
    return { district: 'Kohima', policeStation: 'North Police Station' };
  }
  
  // Default fallback
  return { district: 'Guwahati', policeStation: 'Fancy Bazar Police Station' };
};

// Auto-generate FIR for tourist in distress
// In-memory storage for FIR data (not persisted to database)
let inMemoryFIRs: FIRData[] = [];
let firIdCounter = 0;

// Generate FIR from tourist data without storing in database
export const generateFIRFromTourist = (touristData: any): FIRData => {
  const caseNumber = generateFIRNumber();
  const { district, policeStation } = getPoliceStationByLocation(
    touristData.latitude || touristData.location?.latitude || 26.1445,
    touristData.longitude || touristData.location?.longitude || 91.7362
  );
  
  const now = Timestamp.now();
  firIdCounter++;
  
  const firData: FIRData = {
    id: `fir_${firIdCounter}`,
    caseNumber,
    date: now,
    touristId: touristData.id || touristData.touristId,
    touristName: touristData.name || 'Unknown Tourist',
    touristEmail: touristData.email || 'Unknown',
    touristPhone: touristData.phone,
    incidentType: 'Emergency SOS Alert',
    incidentDetails: `Auto-generated FIR due to SOS alert from tourist. Tourist "${touristData.name}" reported as being in distress. Location: ${touristData.address || 'Unknown location'}. Immediate assistance required.`,
    location: {
      latitude: touristData.latitude || touristData.location?.latitude || 26.1445,
      longitude: touristData.longitude || touristData.location?.longitude || 91.7362,
      address: touristData.address || touristData.location?.address || 'Unknown location'
    },
    district,
    policeStation,
    status: 'Active',
    priority: 'High',
    createdAt: now,
    updatedAt: now,
    isAutoGenerated: true,
    section: 'Emergency Response Protocol - Section 144',
    additionalDetails: `Tourist Details: ${touristData.name || 'N/A'}, Contact: ${touristData.phone || 'N/A'}. This FIR was automatically generated by the Raahi Northeast Explorer emergency response system based on real-time distress alert.`
  };
  
  // Add to in-memory storage
  inMemoryFIRs.push(firData);
  
  return firData;
};

// Get distressed tourists and generate FIRs dynamically
export const getDistressedTouristFIRs = async (): Promise<FIRData[]> => {
  try {
    const touristsQuery = query(
      collection(db, 'tourist'),
      where('isInDistress', '==', true)
    );
    
    const snapshot = await getDocs(touristsQuery);
    const distressedTourists = snapshot.docs.map(doc => ({ 
      id: doc.id, 
      ...doc.data() 
    }));
    
    // Generate FIRs for each distressed tourist
    const generatedFIRs = distressedTourists.map(tourist => {
      // Check if we already have an in-memory FIR for this tourist
      const existingFIR = inMemoryFIRs.find(fir => fir.touristId === tourist.id);
      if (existingFIR) {
        return existingFIR;
      }
      
      // Generate new FIR
      return generateFIRFromTourist(tourist);
    });
    
    return generatedFIRs;
  } catch (error) {
    console.error('Error fetching distressed tourists:', error);
    return [];
  }
};

// Update FIR status (in-memory only)
export const updateFIRStatusInMemory = (firId: string, status: FIRData['status'], additionalDetails?: string): boolean => {
  const firIndex = inMemoryFIRs.findIndex(fir => fir.id === firId);
  if (firIndex !== -1) {
    inMemoryFIRs[firIndex] = {
      ...inMemoryFIRs[firIndex],
      status,
      updatedAt: Timestamp.now(),
      additionalDetails: additionalDetails || inMemoryFIRs[firIndex].additionalDetails
    };
    return true;
  }
  return false;
};

// Get FIR by ID (from in-memory storage or generate from tourist data)
export const getFIRById = async (firId: string): Promise<FIRData | null> => {
  // First check in-memory storage
  const memoryFIR = inMemoryFIRs.find(fir => fir.id === firId);
  if (memoryFIR) {
    return memoryFIR;
  }
  
  // If not found, try to find the tourist and generate FIR
  try {
    const touristsQuery = query(collection(db, 'tourist'));
    const snapshot = await getDocs(touristsQuery);
    const tourists = snapshot.docs.map(doc => ({ id: doc.id, ...doc.data() }));
    
    // Find a distressed tourist and generate FIR with the requested ID
    const distressedTourist = tourists.find((t: any) => t.isInDistress);
    if (distressedTourist) {
      const fir = generateFIRFromTourist(distressedTourist);
      fir.id = firId; // Override with requested ID
      return fir;
    }
  } catch (error) {
    console.error('Error fetching tourist for FIR:', error);
  }
  
  return null;
};

// Update FIR status (use in-memory version)
export const updateFIRStatus = async (firId: string, status: FIRData['status'], additionalDetails?: string): Promise<void> => {
  updateFIRStatusInMemory(firId, status, additionalDetails);
};

// Monitor distressed tourists (simplified - just for notifications)
export const startDistressMonitoring = () => {
  console.log('Started monitoring tourist distress status for FIR generation');
  
  // Return a dummy unsubscribe function since we're not actually monitoring
  return () => {
    console.log('Stopped monitoring tourist distress status');
  };
};

// Subscribe to active FIRs (generate from distressed tourists)
export const subscribeActiveFIRs = (callback: (firs: FIRData[]) => void) => {
  const fetchActiveFIRs = async () => {
    const firs = await getDistressedTouristFIRs();
    const activeFIRs = firs.filter(fir => fir.status === 'Active' || fir.status === 'Under Investigation');
    callback(activeFIRs);
  };

  // Initial fetch
  fetchActiveFIRs();

  // Set up periodic refresh to get real-time updates
  const interval = setInterval(fetchActiveFIRs, 5000); // Refresh every 5 seconds

  // Return unsubscribe function
  return () => {
    clearInterval(interval);
  };
};

// Subscribe to past FIRs (from in-memory storage)
export const subscribePastFIRs = (callback: (firs: FIRData[]) => void) => {
  const fetchPastFIRs = () => {
    const pastFIRs = inMemoryFIRs.filter(fir => fir.status === 'Closed' || fir.status === 'Pending');
    callback(pastFIRs);
  };

  // Initial fetch
  fetchPastFIRs();

  // Set up periodic refresh
  const interval = setInterval(fetchPastFIRs, 5000);

  // Return unsubscribe function
  return () => {
    clearInterval(interval);
  };
};