import React, { useEffect, useState } from 'react';
import { Link, useNavigate } from 'react-router-dom';
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { AlertTriangle, Clock, MapPin, Phone, User } from "lucide-react";
import { useTranslation } from 'react-i18next';
import { subscribeActiveFIRs, subscribePastFIRs, FIRData, startDistressMonitoring } from '@/lib/firService';

const EFIR: React.FC = () => {
  const { t } = useTranslation();
  const navigate = useNavigate();
  const [activeFIRs, setActiveFIRs] = useState<FIRData[]>([]);
  const [pastFIRs, setPastFIRs] = useState<FIRData[]>([]);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    // Start monitoring tourist distress for auto-FIR generation
    const unsubscribeDistressMonitoring = startDistressMonitoring();

    // Subscribe to active FIRs
    const unsubscribeActiveFIRs = subscribeActiveFIRs((firs) => {
      setActiveFIRs(firs);
      setLoading(false);
    });

    // Subscribe to past FIRs
    const unsubscribePastFIRs = subscribePastFIRs((firs) => {
      setPastFIRs(firs);
    });

    return () => {
      unsubscribeDistressMonitoring();
      unsubscribeActiveFIRs();
      unsubscribePastFIRs();
    };
  }, []);

  const formatDate = (timestamp: any) => {
    if (timestamp?.toDate) {
      return timestamp.toDate().toLocaleDateString();
    }
    return new Date(timestamp).toLocaleDateString();
  };

  const getPriorityColor = (priority: string) => {
    switch (priority) {
      case 'High': return 'bg-red-100 text-red-800';
      case 'Medium': return 'bg-yellow-100 text-yellow-800';
      case 'Low': return 'bg-green-100 text-green-800';
      default: return 'bg-gray-100 text-gray-800';
    }
  };

  if (loading) {
    return (
      <div className="p-8 bg-gradient-to-br from-green-50 to-golden-50 min-h-screen text-gray-800">
        <div className="flex items-center justify-center min-h-[400px]">
          <div className="text-lg text-green-700">Loading FIRs...</div>
        </div>
      </div>
    );
  }

  return (
    <div className="p-8 bg-gradient-to-br from-green-50 to-golden-50 min-h-screen text-gray-800">
      <div className="flex items-center justify-between mb-10">
        <h1 className="text-3xl md:text-4xl font-bold text-center bg-gradient-to-r from-golden to-green bg-clip-text text-transparent">{t('eFirDashboard')}</h1>
        <Button variant="outline" onClick={() => navigate('/authority')}>{t('backToDashboard')}</Button>
      </div>
      <div className="container mx-auto max-w-6xl bg-white rounded-xl shadow-lg p-8">
        <div className="mb-10 p-6 bg-card rounded-lg shadow-inner">
          <h2 className="text-3xl font-bold mb-6 text-green-800 border-b-2 border-border pb-2 flex items-center">
            <AlertTriangle className="w-8 h-8 mr-3 text-red-500" />
            {t('activeFirs')} ({activeFIRs.length})
          </h2>
          {activeFIRs.length === 0 ? (
            <p className="text-green-700 text-lg">{t('noActiveFirs')}</p>
          ) : (
            <ul className="space-y-4">
              {activeFIRs.map((fir) => (
                <li key={fir.id} className={`bg-white p-5 rounded-lg shadow-md hover:shadow-lg transition-all duration-300 border-l-4 ${fir.isAutoGenerated ? 'border-l-red-500' : 'border-l-green-500'}`}>
                  <Link to={`/fir-details/${fir.id}`} className="text-green-800 hover:text-golden-800 hover:underline">
                    <div className="flex items-start justify-between">
                      <div className="flex-1">
                        <div className="flex items-center gap-3 mb-2">
                          <h3 className="font-semibold text-xl">{fir.touristName}</h3>
                          {fir.isAutoGenerated && (
                            <Badge className="bg-red-100 text-red-800 text-xs">AUTO-GENERATED</Badge>
                          )}
                          <Badge className={`text-xs ${getPriorityColor(fir.priority)}`}>
                            {fir.priority} Priority
                          </Badge>
                        </div>
                        <p className="text-golden-600 text-base font-normal mb-2">
                          {t('firNo', { caseNumber: fir.caseNumber })}
                        </p>
                        <div className="grid grid-cols-1 md:grid-cols-2 gap-2 text-sm text-gray-600">
                          <div className="flex items-center">
                            <User className="w-4 h-4 mr-2" />
                            {fir.touristEmail}
                          </div>
                          <div className="flex items-center">
                            <MapPin className="w-4 h-4 mr-2" />
                            {fir.district}
                          </div>
                          <div className="flex items-center">
                            <Clock className="w-4 h-4 mr-2" />
                            {formatDate(fir.date)}
                          </div>
                          <div className="flex items-center">
                            <AlertTriangle className="w-4 h-4 mr-2" />
                            {fir.incidentType}
                          </div>
                        </div>
                        <p className="text-sm text-gray-700 mt-2 line-clamp-2">
                          {fir.incidentDetails}
                        </p>
                      </div>
                      <svg xmlns="http://www.w3.org/2000/svg" className="h-6 w-6 text-green-400 flex-shrink-0" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                        <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M9 5l7 7-7 7" />
                      </svg>
                    </div>
                  </Link>
                </li>
              ))}
            </ul>
          )}
        </div>

        <div className="p-6 bg-card rounded-lg shadow-inner">
          <h2 className="text-3xl font-bold mb-6 text-golden-800 border-b-2 border-border pb-2 flex items-center">
            <Clock className="w-8 h-8 mr-3 text-golden-600" />
            {t('pastFirs')} ({pastFIRs.length})
          </h2>
          {pastFIRs.length === 0 ? (
            <p className="text-golden-700 text-lg">{t('noPastFirs')}</p>
          ) : (
            <ul className="space-y-4">
              {pastFIRs.map((fir) => (
                <li key={fir.id} className="bg-white p-5 rounded-lg shadow-md hover:shadow-lg transition-all duration-300 border-l-4 border-l-golden-500">
                  <Link to={`/fir-details/${fir.id}`} className="text-golden-800 hover:text-green-800 hover:underline">
                    <div className="flex items-start justify-between">
                      <div className="flex-1">
                        <div className="flex items-center gap-3 mb-2">
                          <h3 className="font-semibold text-xl">{fir.touristName}</h3>
                          {fir.isAutoGenerated && (
                            <Badge className="bg-red-100 text-red-800 text-xs">AUTO-GENERATED</Badge>
                          )}
                          <Badge className="bg-gray-100 text-gray-800 text-xs">CLOSED</Badge>
                        </div>
                        <p className="text-green-600 text-base font-normal mb-2">
                          {t('firNo', { caseNumber: fir.caseNumber })}
                        </p>
                        <div className="grid grid-cols-1 md:grid-cols-2 gap-2 text-sm text-gray-600">
                          <div className="flex items-center">
                            <User className="w-4 h-4 mr-2" />
                            {fir.touristEmail}
                          </div>
                          <div className="flex items-center">
                            <MapPin className="w-4 h-4 mr-2" />
                            {fir.district}
                          </div>
                          <div className="flex items-center">
                            <Clock className="w-4 h-4 mr-2" />
                            {formatDate(fir.date)}
                          </div>
                          <div className="flex items-center">
                            <AlertTriangle className="w-4 h-4 mr-2" />
                            {fir.incidentType}
                          </div>
                        </div>
                        <p className="text-sm text-gray-700 mt-2 line-clamp-2">
                          {fir.incidentDetails}
                        </p>
                      </div>
                      <svg xmlns="http://www.w3.org/2000/svg" className="h-6 w-6 text-golden-400 flex-shrink-0" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                        <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M9 5l7 7-7 7" />
                      </svg>
                    </div>
                  </Link>
                </li>
              ))}
            </ul>
          )}
        </div>
      </div>
    </div>
  );
};

export default EFIR;