import React, { useEffect, useState } from 'react';
import { useParams, useNavigate } from 'react-router-dom';
import { Button } from '@/components/ui/button';
import { Badge } from '@/components/ui/badge';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { AlertTriangle, MapPin, Clock, User, Phone, Mail, FileText, Shield, ArrowLeft } from 'lucide-react';
import { useTranslation } from 'react-i18next';
import { FIRData, updateFIRStatus, getFIRById } from '@/lib/firService';

const FIRDetails: React.FC = () => {
  const { id } = useParams<{ id: string }>();
  const navigate = useNavigate();
  const { t } = useTranslation();
  const [fir, setFir] = useState<FIRData | null>(null);
  const [loading, setLoading] = useState(true);
  const [updating, setUpdating] = useState(false);

  useEffect(() => {
    if (!id) {
      navigate('/e-fir');
      return;
    }

    const fetchFIR = async () => {
      try {
        const firData = await getFIRById(id);
        
        if (firData) {
          setFir(firData);
        } else {
          console.error('FIR not found');
          navigate('/e-fir');
        }
      } catch (error) {
        console.error('Error fetching FIR:', error);
        navigate('/e-fir');
      } finally {
        setLoading(false);
      }
    };

    fetchFIR();
  }, [id, navigate]);

  const handleStatusUpdate = async (newStatus: FIRData['status']) => {
    if (!fir || !id) return;

    setUpdating(true);
    try {
      await updateFIRStatus(id, newStatus, `Status updated to ${newStatus} by authority`);
      setFir({ ...fir, status: newStatus });
    } catch (error) {
      console.error('Error updating FIR status:', error);
    } finally {
      setUpdating(false);
    }
  };

  const formatDate = (timestamp: any) => {
    if (timestamp?.toDate) {
      return timestamp.toDate().toLocaleString();
    }
    return new Date(timestamp).toLocaleString();
  };

  const getStatusColor = (status: string) => {
    switch (status) {
      case 'Active': return 'bg-red-100 text-red-800';
      case 'Under Investigation': return 'bg-blue-100 text-blue-800';
      case 'Closed': return 'bg-green-100 text-green-800';
      case 'Pending': return 'bg-yellow-100 text-yellow-800';
      default: return 'bg-gray-100 text-gray-800';
    }
  };

  const getPriorityColor = (priority: string) => {
    switch (priority) {
      case 'High': return 'bg-red-100 text-red-800';
      case 'Medium': return 'bg-yellow-100 text-yellow-800';
      case 'Low': return 'bg-green-100 text-green-800';
      default: return 'bg-gray-100 text-gray-800';
    }
  };

  if (loading) {
    return (
      <div className="p-8 bg-gradient-to-br from-green-50 to-golden-50 min-h-screen">
        <div className="flex items-center justify-center min-h-[400px]">
          <div className="text-lg text-green-700">Loading FIR details...</div>
        </div>
      </div>
    );
  }

  if (!fir) {
    return (
      <div className="p-8 bg-gradient-to-br from-green-50 to-golden-50 min-h-screen">
        <div className="flex items-center justify-center min-h-[400px]">
          <div className="text-lg text-red-700">FIR not found</div>
        </div>
      </div>
    );
  }

  return (
    <div className="p-8 bg-gradient-to-br from-green-50 to-golden-50 min-h-screen">
      <div className="container mx-auto max-w-4xl">
        <div className="flex items-center justify-between mb-8">
          <div className="flex items-center">
            <Button
              variant="outline"
              onClick={() => navigate('/e-fir')}
              className="mr-4"
            >
              <ArrowLeft className="w-4 h-4 mr-2" />
              Back to FIRs
            </Button>
            <h1 className="text-3xl font-bold bg-gradient-to-r from-green-600 to-golden-600 bg-clip-text text-green">
              FIR Details
            </h1>
          </div>
          <div className="flex items-center gap-3">
            {fir.isAutoGenerated && (
              <Badge className="bg-red-100 text-red-800">
                <AlertTriangle className="w-4 h-4 mr-1" />
                AUTO-GENERATED
              </Badge>
            )}
            <Badge className={`${getPriorityColor(fir.priority)}`}>
              {fir.priority} Priority
            </Badge>
            <Badge className={`${getStatusColor(fir.status)}`}>
              {fir.status}
            </Badge>
          </div>
        </div>

        <div className="grid gap-6">
          <Card className="border-green-200 shadow-lg">
            <CardHeader className="bg-gradient-to-r from-green-50 to-golden-50">
              <CardTitle className="flex items-center text-green-800">
                <FileText className="w-6 h-6 mr-3" />
                FIR Summary
              </CardTitle>
            </CardHeader>
            <CardContent className="p-6">
              <div className="grid md:grid-cols-2 gap-6">
                <div>
                  <h3 className="text-lg font-semibold mb-4">Case Information</h3>
                  <div className="space-y-3">
                    <div className="flex items-start">
                      <FileText className="w-5 h-5 mr-3 mt-0.5 text-green-600" />
                      <div>
                        <p className="font-medium">Case Number</p>
                        <p className="text-gray-600">{fir.caseNumber}</p>
                      </div>
                    </div>
                    <div className="flex items-start">
                      <Clock className="w-5 h-5 mr-3 mt-0.5 text-green-600" />
                      <div>
                        <p className="font-medium">Date Filed</p>
                        <p className="text-gray-600">{formatDate(fir.date)}</p>
                      </div>
                    </div>
                    <div className="flex items-start">
                      <AlertTriangle className="w-5 h-5 mr-3 mt-0.5 text-green-600" />
                      <div>
                        <p className="font-medium">Incident Type</p>
                        <p className="text-gray-600">{fir.incidentType}</p>
                      </div>
                    </div>
                  </div>
                </div>

                <div>
                  <h3 className="text-lg font-semibold mb-4">Tourist Information</h3>
                  <div className="space-y-3">
                    <div className="flex items-start">
                      <User className="w-5 h-5 mr-3 mt-0.5 text-blue-600" />
                      <div>
                        <p className="font-medium">Name</p>
                        <p className="text-gray-600">{fir.touristName}</p>
                      </div>
                    </div>
                    <div className="flex items-start">
                      <Mail className="w-5 h-5 mr-3 mt-0.5 text-blue-600" />
                      <div>
                        <p className="font-medium">Email</p>
                        <p className="text-gray-600">{fir.touristEmail}</p>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </CardContent>
          </Card>

          <Card className="border-blue-200 shadow-lg">
            <CardHeader className="bg-gradient-to-r from-blue-50 to-indigo-50">
              <CardTitle className="flex items-center text-blue-800">
                <MapPin className="w-6 h-6 mr-3" />
                Location Information
              </CardTitle>
            </CardHeader>
            <CardContent className="p-6">
              <div className="grid md:grid-cols-2 gap-6">
                <div>
                  <div className="space-y-3">
                    <div>
                      <p className="font-medium">District</p>
                      <p className="text-gray-600">{fir.district}</p>
                    </div>
                    <div>
                      <p className="font-medium">Police Station</p>
                      <p className="text-gray-600">{fir.policeStation}</p>
                    </div>
                  </div>
                </div>
                <div>
                  <div className="space-y-3">
                    <div>
                      <p className="font-medium">Coordinates</p>
                      <p className="text-gray-600">
                        {fir.location.latitude.toFixed(6)}, {fir.location.longitude.toFixed(6)}
                      </p>
                    </div>
                  </div>
                </div>
              </div>
            </CardContent>
          </Card>

          <Card className="border-yellow-200 shadow-lg">
            <CardHeader className="bg-gradient-to-r from-yellow-50 to-amber-50">
              <CardTitle className="flex items-center text-yellow-800">
                <FileText className="w-6 h-6 mr-3" />
                Incident Details
              </CardTitle>
            </CardHeader>
            <CardContent className="p-6">
              <div className="space-y-4">
                <div>
                  <p className="font-medium mb-2">Description</p>
                  <p className="text-gray-700 leading-relaxed">{fir.incidentDetails}</p>
                </div>
              </div>
            </CardContent>
          </Card>

          <Card className="border-gray-200 shadow-lg">
            <CardHeader className="bg-gradient-to-r from-gray-50 to-slate-50">
              <CardTitle className="text-gray-800">Actions</CardTitle>
            </CardHeader>
            <CardContent className="p-6">
              <div className="flex flex-wrap gap-3">
                <Button
                  onClick={() => handleStatusUpdate('Under Investigation')}
                  disabled={updating || fir.status === 'Under Investigation' || fir.status === 'Closed'}
                  variant={fir.status === 'Under Investigation' ? 'default' : 'outline'}
                  className="flex items-center"
                >
                  <Shield className="w-4 h-4 mr-2" />
                  Mark Under Investigation
                </Button>
                <Button
                  onClick={() => handleStatusUpdate('Closed')}
                  disabled={updating || fir.status === 'Closed'}
                  variant={fir.status === 'Closed' ? 'default' : 'outline'}
                  className="flex items-center"
                >
                  <FileText className="w-4 h-4 mr-2" />
                  Close FIR
                </Button>
              </div>
              {updating && (
                <p className="text-sm text-gray-600 mt-2">Updating status...</p>
              )}
            </CardContent>
          </Card>
        </div>
      </div>
    </div>
  );
};

export default FIRDetails;